apiVersion: v1
kind: Service
metadata:
  namespace: default
  name: backend-svc
spec:
  type: NodePort
  selector:
    app: backend
  ports:
    - port: 2346
      protocol: TCP
      targetPort: 3301
