apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-dep
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: PROJECT/IMAGE
          resources:
            limits:
              cpu: "300m"
              memory: "300Mi"
          env:
          - name: POSTGRES_PASSWORD
            valueFrom:
              secretKeyRef:
                name: dbpassword
                key: POSTGRES_PASSWORD
          - name: POSTGRES_USER
            valueFrom:
              configMapKeyRef:
                name: configmap
                key: POSTGRES_USER
          - name: POSTGRES_DB
            valueFrom:
              configMapKeyRef:
                name: configmap
                key: POSTGRES_DB
