apiVersion: batch/v1
kind: CronJob
metadata:
  namespace: default
  name: cronjob
spec:
  schedule: "0 0 * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: cronjob
            image: tonip57/urlcronjob
          restartPolicy: OnFailure
