apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- cronjob.yaml
images:
- name: IMAGE_PLACEHOLDER
  newName: tonip57/urlcronjob
  newTag: 1024ff1b20326af10513267d8ed628a87d407bdc
