apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- cronjob.yaml
images:
- name: IMAGE_PLACEHOLDER
  newName: tonip57/urlcronjob
  newTag: 196c66e0d309cc593523113913510449e1d81a02
