apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- rollout.yaml
- configmap.yaml
- secret.yaml
- service.yaml
- statefulset.yaml
images:
- name: IMAGE_PLACEHOLDER
  newName: tonip57/backend
  newTag: ea9a62192d792dc92ba34d8c8705af1d90e06b74
