apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yaml
- configmap.yaml
- secret.yaml
- service.yaml
- statefulset.yaml
images:
- name: IMAGE_PLACEHOLDER
  newName: tonip57/backend
  newTag: 2668fdd10c0870943a2d35a4a5577bc75c5a1675
