apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  namespace: default
  name: backend-dep
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  strategy:
    canary:
      steps:
      - setWeight: 50
      - analysis:
          templates:
          - templateName: rate
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: IMAGE_PLACEHOLDER
          readinessProbe:
            initialDelaySeconds: 20 # Initial delay until the readiness is tested
            periodSeconds: 30 # How often to test
            httpGet:
              path: /healthz
              port: 3301
          livenessProbe:
            initialDelaySeconds: 20 # Initial delay until the liveness is tested
            periodSeconds: 30 # How often to test
            httpGet:
              path: /healthz
              port: 3301
          resources:
            limits:
              cpu: "250m"
              memory: "250Mi"
          env:
          - name: POSTGRES_PASSWORD
            valueFrom:
              secretKeyRef:
                name: dbpassword
                key: POSTGRES_PASSWORD
          - name: POSTGRES_USER
            valueFrom:
              configMapKeyRef:
                name: configmap
                key: POSTGRES_USER
          - name: POSTGRES_DB
            valueFrom:
              configMapKeyRef:
                name: configmap
                key: POSTGRES_DB
          - name: NATS_URL
            value: nats://my-nats:4222
