apiVersion: v1
kind: Service
metadata:
  namespace: logoutput
  name: pingpong-svc
spec:
  type: ClusterIP
  selector:
    app: pingpong
  ports:
    - name: http
      port: 2345
      protocol: TCP
      targetPort: 3301