apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: default
  name: broadcaster-dep
spec:
  replicas: 2
  selector:
    matchLabels:
      app: broadcaster
  template:
    metadata:
      labels:
        app: broadcaster
    spec:
      containers:
        - name: broadcaster
          image: IMAGE_PLACEHOLDER
          env:
          - name: NATS_URL
            value: nats://my-nats:4222
          - name: TG_API_KEY
            valueFrom:
              secretKeyRef:
                name: broadcaster-secrets
                key: TG_API_KEY
          - name: CHAT_ID
            valueFrom:
              secretKeyRef:
                name: broadcaster-secrets
                key: CHAT_ID
