apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yaml
- secret.yaml
images:
- name: IMAGE_PLACEHOLDER
  newName: tonip57/broadcaster
  newTag: 76dc696f605bc1834dba99d8c8062b56d5d12256
