apiVersion: v1
kind: Secret
metadata:
    namespace: project
    name: broadcaster-secrets
stringData:
    TG_API_KEY: "5447181216:AAFs0c3_ep7mVlTBHBTMI6mnjQWe_iMiAkU"
    CHAT_ID: "5406790321"