apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: project
  name: backend-dep
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: tonip57/backend
          env:
          - name: POSTGRES_PASSWORD
            valueFrom:
              secretKeyRef:
                name: dbpassword
                key: POSTGRES_PASSWORD
          - name: POSTGRES_USER
            valueFrom:
              configMapKeyRef:
                name: configmap
                key: POSTGRES_USER
          - name: POSTGRES_DB
            valueFrom:
              configMapKeyRef:
                name: configmap
                key: POSTGRES_DB