apiVersion: v1
kind: Service
metadata:
  namespace: project
  name: backend-svc
spec:
  type: ClusterIP
  selector:
    app: backend
  ports:
    - port: 2345
      protocol: TCP
      targetPort: 3301