apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: pingpong
  namespace: logoutput
spec:
  template:
    metadata:
      name: pingpong-v1
    spec:
      containers:
        - image: tonip57/pingpong
          env:
          - name: POSTGRES_PASSWORD
            valueFrom:
              secretKeyRef:
                name: dbpassword
                key: POSTGRES_PASSWORD