apiVersion: v1
kind: Service
metadata:
  namespace: logoutput
  name: pingpong-svc
spec:
  type: NodePort
  selector:
    app: pingpong
  ports:
    - port: 8080
      protocol: TCP
      targetPort: 8080