apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- manifests/deployment.yaml
- manifests/configmap.yaml
- manifests/secret.yaml
- manifests/service.yaml
- manifests/statefulset.yaml
images:
- name: IMAGE_PLACEHOLDER
  newName: tonip57/backend
