apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yaml
- ingress.yaml
- persistentvolumeclaim.yaml
- service.yaml
images:
- name: IMAGE_PLACEHOLDER
  newName: tonip57/webserver
  newTag: 2d5e03b9707b215f14f4d7a6e52b7d410a14be74
