apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- analysistemplate.yaml
- rollout.yaml
- ingress.yaml
- persistentvolumeclaim.yaml
- service.yaml
images:
- name: IMAGE_PLACEHOLDER
  newName: tonip57/webserver
  newTag: dc038aa51ab8bd9fc900f990f2e8b2afa388dbb9
