name: Release broadcaster-go

on:
  push:
    branches:
      - main
    paths:
      - 'part4/project/broadcaster/**'
      - '.github/workflows/broadcaster-go.yml'

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and Push
      uses: docker/build-push-action@v2
      with:
        context: part4/project/broadcaster
        push: true
        tags: tonip57/broadcaster:${{ github.sha }}

  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    needs: build

    steps:
    - uses: actions/checkout@v2

    # Set up kustomize
    - name: Set up Kustomize
      uses: imranismail/setup-kustomize@v1

    # Update yamls
    - name: Update yamls
      working-directory: part4/project/broadcaster/manifests
      run: |-
        kustomize edit set image IMAGE_PLACEHOLDER=tonip57/broadcaster:${{ github.sha }}
    # Commit and push
    - uses: EndBug/add-and-commit@v7
      with:
        add: 'part4/project/broadcaster/manifests/kustomization.yaml'
        message: New version release for broadcaster ${{ github.sha }}
      env:
        GITHUB_TOKEN: ${{ secrets.GIT_TOKEN }}
